---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "hcbille.se - Server"
subtitle: "Dashboard"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false
# Optional theme customization
stylesheet:
  - "assets/custom.css"
  
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:

  - name: "Tailscale!"
    icon: "fa-solid fa-scale-unbalanced"
    url: "#tailscale" 

  - name: "Portainer"
    logo: "assets/icons/png/portainer.png"
    url: "https://portainer.hcbille.se" 
# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Services"
    icon: "fas fa-cloud"
    items:
      - name: "Jellyfin"
        logo: "assets/icons/png/jellyfin.png"
        subtitle: "Local Netflix"
        url: "https://jellyfin.hcbille.se"

      - name: "Jellyseerr"
        logo: "assets/icons/png/overseerr.png"
        subtitle: "Request movies/series for Jellyfin"
        url: "https://jellyseerr.hcbille.se"

      - name: "Audiobookshelf"
        logo: "assets/icons/png/bookstack.png"
        subtitle: "Podcasts"
        url: "https://audiobook.hcbille.se/"

      - name: "Calibre-Web"
        logo: "assets/icons/png/calibreweb.png"
        subtitle: "Book-management"
        tag: "books"
        url: "https://calibre-web.hcbille.se/"

      - name: "Kavita"
        logo: "assets/icons/png/kavita.png"
        subtitle: "Book-reader"
        tag: "books"
        url: "https://calibre-web.hcbille.se/"


        
  - name: "Tailscale"
    icon: "fas fa-cloud"
    items:
      - name: "FileBroswer"
        logo: "assets/icons/png/filebrowser.png"
        subtitle: "Server-filebroswer"
        url: "http://newserver:6969/"
      
      - name: "VS-code"
        logo: "assets/icons/png/codeserver.png"
        subtitle: "VS-Code"
        url: "http://newserver:8443/"