---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "hcbille.se - Server"
subtitle: "Dashboard"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false
# Optional theme customization
stylesheet:
  - "assets/custom.css"
  
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:

  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  - name: "Internal!"
    icon: "fas fa-file-alt"
    url: "#internal" 

  - name: "Portainer"
    logo: "assets/icons/png/portainer.png"
    url: "https://portainer.hcbille.se" 
# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Services"
    icon: "fas fa-cloud"
    items:
      - name: "Jellyfin"
        logo: "assets/icons/png/jellyfin.png"
        subtitle: "Local Netflix"
        url: "https://jellyfin.hcbille.se"

      - name: "Jellyseerr"
        logo: "assets/icons/png/overseerr.png"
        subtitle: "Request movies/series for Jellyfin"
        url: "https://jellyseerr.hcbille.se"

      - name: "Calibre"
        logo: "assets/icons/png/calibreweb.png"
        subtitle: "Library"
        url: "https://calibre.hcbille.se"

      - name: "Audiobookshelf"
        logo: "assets/icons/png/bookstack.png"
        subtitle: "Library"
        url: "https://audiobook.hcbille.se/"

      - name: "FreshRSS"
        logo: "assets/icons/png/freshrss.png"
        subtitle: "Library"
        url: "https://freshrss.hcbille.se/"

  - name: "Tools"
    icon: "fas fa-wrench"
    items:
      - name: "Code-server"
        logo: "assets/icons/png/codeserver.png"
        subtitle: "Cloud VSCode"
        url: "https://code-server.hcbille.se"

      - name: "Filebrowser"
        icon: "fas fa-folder"
        subtitle: "Move files"
        url: "https://filebrowser.hcbille.se"

      - name: "Calibre-db"
        logo: "assets/icons/png/calibreweb.png"
        subtitle: "Library-db"
        url: "https://calibre-db.hcbille.se"
      